version: "3.8"
name: project
services:
  nodeapp:
    build:
     context: ./backend
     dockerfile: Dockerfile
    container_name: proj_backend
    ports:
      - "5000:4000"
    depends_on:
      - mongodb
    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        - path: ./backend
          target: /usr/src/app
          action: sync


  mongodb:
    image: mongo
    container_name: proj_mongo
    ports:
      - "27071:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - project-data:/data/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: proj_frontend 
    ports:
      - "5173:5173"
    depends_on:
      - nodeapp
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

volumes:
  project-data:
    driver: local
